version: '3'

services:
  2104-wns-paris-agowork-back:
    build: ../2104-wns-paris-agowork-back
    command: sh -c "npm run build && npm run prod"
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
    depends_on:
      - mongodb
  2104-wns-paris-agowork-front:
    build: ./
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production  
  mongodb:
    image: mongo:4.4.9
    volumes:
      - ../data:/data/db
    env_file: 
      - .env
    environment:
      - MONGO_PASSWORD=${DB_PASS} \
      - MONGO_DATABASE=${DB_DATABASE} \
  nginx:
    image: nginx:1.21.3
    depends_on:
      - 2104-wns-paris-agowork-back
      - 2104-wns-paris-agowork-front
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build: