services:
  2104-wns-paris-agowork-back:
    container_name: agowork_back
    build: ../2104-wns-paris-agowork-back
    volumes:
      - ../2104-wns-paris-agowork-back/src/:/app/src/
    ports:
      - 4001:4000
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ../data:/data/db
  2104-wns-paris-agowork-front:
    container_name: agowork_front
    build: ./
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src/
    environment:
      - CHOKIDAR_USEPOLLING=true