services:
    mongodb:
      image: mongo
      container_name: mongodb
      hostname: mongodb
      volumes:
        - ../data:/data/db
      env_file: 
        - .env.local
      environment:
        - MONGO_PORT=${DB_PORT} \
        - MONGO_DATABASE=${DB_DATABASE} \
    2104-wns-paris-agowork-front:
      container_name: agowork_front
      build: ./
      ports:
        - 3001:3000
      volumes:
        - ./src:/app/src/
      environment:
        - CHOKIDAR_USEPOLLING=true

    2104-wns-paris-agowork-back:
      container_name: agowork_back
      build: ../${FILE_BACK}
      command: npm run dev
      volumes:
        - ../${FILE_BACK}/src/:/app/src/
      env_file: 
        - ../${FILE_BACK}/.env.local
      ports:
        - 4001:4000