services:
    2104-wns-paris-agowork-back:
      build: ../2104-wns-paris-agowork-back
      command: npm run dev
      volumes:
        - ../2104-wns-paris-agowork-back/src/:/app/src/
      ports:
        - 4001:4000
    mongodb:
      image: mongo
      volumes:
        - ../data:/data/db
    2104-wns-paris-agowork-front:
      build: ./
      ports:
        - 3001:3000
      volumes:
        - ./src:/app/src/
      environment:
        - CHOKIDAR_USEPOLLING=true