name: docker-ci

on:
  push:
    branches:
      - "master"

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: run tests for 2104-wns-paris-agowork-front
        run: npm install && npm run test
